services:
  webapp:
    container_name: webapp
    build:
      context: .
    command: [ "sh", "/scripts/commands.sh" ]
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:15-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
