# Generated by Django 6.0.3 on 2026-03-16 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Compras',
                'verbose_name_plural': 'Listas de Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Produto')),
                ('quantity_value', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantidade')),
                ('unit', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('L', 'Litro'), ('ml', 'Mililitro'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('dz', 'Dúzia')], default='un', max_length=10, verbose_name='Unidade')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço unitário')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Comprado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyShoppingBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Período (mês ref.)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Orçamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento Mensal',
                'verbose_name_plural': 'Orçamentos Mensais',
                'unique_together': {('user', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ShoppingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Pode editar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_me', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='shopping.shoppinglist')),
            ],
            options={
                'verbose_name': 'Compartilhamento',
                'verbose_name_plural': 'Compartilhamentos',
                'unique_together': {('shopping_list', 'shared_with')},
            },
        ),
    ]
