# Generated by Django 6.0.3 on 2026-03-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='category',
            field=models.CharField(blank=True, default='Geral', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Concluída (Travada)'),
        ),
    ]
