# Generated by Django 6.0.3 on 2026-03-21 00:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppingitem_category_shoppinglist_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Artigo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='Categoria')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='quantity_value',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Série/Ano'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='É um Modelo da Loja?'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='school',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='status',
            field=models.CharField(choices=[('aberta', '🛒 Em Edição (Cliente)'), ('fechada', '🔒 Pedido Concluído'), ('separacao', '📦 Em Separação'), ('pronto', '✅ Pronto para Levantamento'), ('entregue', '🏁 Entregue/Finalizado')], default='aberta', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Estudante'),
        ),
        migrations.AddField(
            model_name='shoppingshare',
            name='invite_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Produto (Manual)'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome da Lista'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.product'),
        ),
    ]
